# .goreleaser.yml
project_name: command-count

build:
  main: cmd/node-prune/main.go
  binary: cmc
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
