# .goreleaser.yml
project_name: command-count

# Build customization
builds:
  - main: cmd/cmc/main.go
    binary: cmc
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - LICENSE
